CREATE TABLE workers (
     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(255) NOT NULL,
     position VARCHAR(255) NOT NULL,
     avatar VARCHAR(255) NOT NULL
);

CREATE TABLE tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR,
    time TIMESTAMP,
    status VARCHAR(20),
    performer_id bigint,
    FOREIGN KEY (performer_id) REFERENCES workers (id) ON DELETE SET NULL
);


